 [[cells]]
 name = "index-state-type"
 enable_type_id = true
 location = { file = "build/release/index-state-type" }

 [[cells]]
 name = "info-type"
 enable_type_id = true
 location = { file = "build/release/info-type" }

# Dep group cells
 [[dep_groups]]
 name = "oracle_dep_groups"
 cells = [
   "index-state-type",
   "info-type"
 ]

 # Replace with your own lock if you want to unlock deployed cells.
 # For example the secp256k1 lock
 [lock]
 code_hash = "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8"
 args = "0xbc502a34a430e3e167c82a24db6f9237b15ebf35"
 hash_type = "type"

